### ISSUE TITLE
Update request

### ISSUE THREAD

**Issue by Kristinita** [twsouthwick/github-cli-nuget#1]
Please, update Hub in Chocolatey. Now I can download via Chocolatey only [2.2.1 version](https://chocolatey.org/packages/github-hub), but from that version to the current version a few bugs have been fixed.

Thank you.

**Comment by mislav** [comment]
It looks like this package is named `github-hub`, whereas there is a newer version of hub [published as `hub`](https://chocolatey.org/packages/hub) on Chocolatey community feed. That version is significantly newer, although not the newest.

@dtgm Could we work out something where I set up the newest version of hub always being auto-published to Chocolatey from CI release process?

**Comment by Kristinita** [comment]
@mislav , @dtgm not have activity on GitHub in September 😿 . He not answered on [my pull-request](https://github.com/dtgm/chocolatey-packages/pull/250) about other package. I [wrote](https://groups.google.com/forum/#!topic/chocolatey/RJkpnTyyprg) this on Chocolatey group.

Thanks.

**Comment by twsouthwick** [comment]
Sorry - just saw this. I haven't been actively using the tool so didn't realize it had gotten so far behind releases. I'm fine transferring the project to someone else if they would like to maintain it.

**Comment by mislav** [comment]
@twsouthwick What's the process of publishing to community feed? Could I be given access to publish to `github-hub`? Ideally I would publish to `hub`, but that's owned by @dtgm right now. I would like to automate releases to the community feed.

**Comment by Kristinita** [comment]
[Closed](https://github.com/github/hub/issues/1288#issuecomment-259557053).
